# Generated by Django 4.0.6 on 2022-07-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='김원표', max_length=40, null=True)),
                ('age', models.IntegerField(blank=True, default=20, null=True)),
                ('phone', models.CharField(blank=True, default='none', max_length=50, null=True)),
            ],
        ),
    ]
